"""add year

Revision ID: c7c3a2b86d86
Revises: ceb751dac86f
Create Date: 2020-03-23 11:38:22.491772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c3a2b86d86'
down_revision = 'ceb751dac86f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'year')
    # ### end Alembic commands ###
