"""add models

Revision ID: ceb751dac86f
Revises: 
Create Date: 2020-03-22 20:19:01.118140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb751dac86f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geodata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_1', sa.String(), nullable=True),
    sa.Column('name_2', sa.String(), nullable=True),
    sa.Column('cc_2', sa.String(), nullable=True),
    sa.Column('nat2018', sa.Float(), nullable=True),
    sa.Column('geometry', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('travel_product', sa.String(), nullable=True),
    sa.Column('sessions_ac', sa.Integer(), nullable=True),
    sa.Column('bookings_ac', sa.Integer(), nullable=True),
    sa.Column('revenue_ac', sa.Integer(), nullable=True),
    sa.Column('spend_ac', sa.Float(), nullable=True),
    sa.Column('day_month', sa.Integer(), nullable=True),
    sa.Column('day_week', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('sessions_aa', sa.Integer(), nullable=True),
    sa.Column('bookings_aa', sa.Integer(), nullable=True),
    sa.Column('revenue_aa', sa.Integer(), nullable=True),
    sa.Column('spend_aa', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('birst_category', sa.String(), nullable=True),
    sa.Column('ga_category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('portfolio')
    op.drop_table('geodata')
    # ### end Alembic commands ###
